name: gymsas_api_client
description: Cliente HTTP y GraphQL reutilizable para aplicaciones GymSAS.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  http: ^1.5.0

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
