import 'routine_builder_models.dart';

class RoutineCatalogMockData {
  const RoutineCatalogMockData._();

  static const List<RoutineDraft> savedRoutines = [
    RoutineDraft(
      id: 'routine-1',
      name: 'Hipertrofia Espalda y Biceps',
      durationWeeks: 4,
      days: [
        RoutineDayDraft(
          label: 'Dia 1',
          focus: 'Espalda',
          exercises: [
            RoutineExerciseDraft(
              id: 'r1-e1',
              name: 'Jalon al pecho',
              focus: 'Espalda',
              series: '4',
              repetitions: '10-12',
              weight: '45 kg',
              rest: '75 s',
            ),
            RoutineExerciseDraft(
              id: 'r1-e2',
              name: 'Remo con barra',
              focus: 'Espalda',
              series: '4',
              repetitions: '8-10',
              weight: '50 kg',
              rest: '90 s',
            ),
            RoutineExerciseDraft(
              id: 'r1-e3',
              name: 'Curl con barra Z',
              focus: 'Biceps',
              series: '3',
              repetitions: '10-12',
              weight: '20 kg',
              rest: '60 s',
            ),
          ],
        ),
        RoutineDayDraft(
          label: 'Dia 2',
          focus: 'Pierna',
          exercises: [
            RoutineExerciseDraft(
              id: 'r1-e4',
              name: 'Sentadilla libre',
              focus: 'Pierna',
              series: '4',
              repetitions: '8-10',
              weight: '70 kg',
              rest: '90 s',
            ),
            RoutineExerciseDraft(
              id: 'r1-e5',
              name: 'Prensa',
              focus: 'Pierna',
              series: '4',
              repetitions: '10-12',
              weight: '120 kg',
              rest: '75 s',
            ),
            RoutineExerciseDraft(
              id: 'r1-e6',
              name: 'Femoral acostado',
              focus: 'Pierna',
              series: '3',
              repetitions: '12',
              weight: '35 kg',
              rest: '60 s',
            ),
          ],
        ),
      ],
    ),
    RoutineDraft(
      id: 'routine-2',
      name: 'Push Hombro Pecho Triceps',
      durationWeeks: 6,
      days: [
        RoutineDayDraft(
          label: 'Dia 1',
          focus: 'Pecho',
          exercises: [
            RoutineExerciseDraft(
              id: 'r2-e1',
              name: 'Press de banca plano',
              focus: 'Pecho',
              series: '4',
              repetitions: '8-10',
              weight: '60 kg',
              rest: '90 s',
            ),
            RoutineExerciseDraft(
              id: 'r2-e2',
              name: 'Press inclinado mancuernas',
              focus: 'Pecho',
              series: '3',
              repetitions: '10-12',
              weight: '22 kg',
              rest: '75 s',
            ),
            RoutineExerciseDraft(
              id: 'r2-e3',
              name: 'Fondos en paralelas',
              focus: 'Triceps',
              series: '3',
              repetitions: '12',
              weight: 'Corporal',
              rest: '60 s',
            ),
          ],
        ),
        RoutineDayDraft(
          label: 'Dia 2',
          focus: 'Hombro',
          exercises: [
            RoutineExerciseDraft(
              id: 'r2-e4',
              name: 'Press militar',
              focus: 'Hombro',
              series: '4',
              repetitions: '8-10',
              weight: '35 kg',
              rest: '90 s',
            ),
            RoutineExerciseDraft(
              id: 'r2-e5',
              name: 'Elevaciones laterales',
              focus: 'Hombro',
              series: '4',
              repetitions: '12-15',
              weight: '10 kg',
              rest: '45 s',
            ),
            RoutineExerciseDraft(
              id: 'r2-e6',
              name: 'Extension de triceps en polea',
              focus: 'Triceps',
              series: '3',
              repetitions: '12-15',
              weight: '20 kg',
              rest: '45 s',
            ),
          ],
        ),
      ],
    ),
    RoutineDraft(
      id: 'routine-3',
      name: 'Pierna y Gluteo Progresiva',
      durationWeeks: 8,
      days: [
        RoutineDayDraft(
          label: 'Dia 1',
          focus: 'Pierna',
          exercises: [
            RoutineExerciseDraft(
              id: 'r3-e1',
              name: 'Sentadilla hack',
              focus: 'Pierna',
              series: '4',
              repetitions: '10',
              weight: '80 kg',
              rest: '75 s',
            ),
            RoutineExerciseDraft(
              id: 'r3-e2',
              name: 'Desplantes caminando',
              focus: 'Pierna',
              series: '3',
              repetitions: '12 por pierna',
              weight: '16 kg',
              rest: '60 s',
            ),
            RoutineExerciseDraft(
              id: 'r3-e3',
              name: 'Extension de cuadriceps',
              focus: 'Pierna',
              series: '3',
              repetitions: '15',
              weight: '30 kg',
              rest: '45 s',
            ),
          ],
        ),
        RoutineDayDraft(
          label: 'Dia 2',
          focus: 'Gluteo',
          exercises: [
            RoutineExerciseDraft(
              id: 'r3-e4',
              name: 'Hip thrust',
              focus: 'Gluteo',
              series: '4',
              repetitions: '10-12',
              weight: '90 kg',
              rest: '90 s',
            ),
            RoutineExerciseDraft(
              id: 'r3-e5',
              name: 'Patada en polea',
              focus: 'Gluteo',
              series: '3',
              repetitions: '15',
              weight: '15 kg',
              rest: '45 s',
            ),
            RoutineExerciseDraft(
              id: 'r3-e6',
              name: 'Abduccion en maquina',
              focus: 'Gluteo',
              series: '3',
              repetitions: '20',
              weight: '35 kg',
              rest: '45 s',
            ),
          ],
        ),
      ],
    ),
  ];
}
